[tox]
envlist = docs
skipsdist = True
   
[testenv:docs]
description = Test doc build with specific Sphinx version
passenv =
    DISPLAY
    XAUTHORITY
    WAYLAND_DISPLAY
    XDG_RUNTIME_DIR
deps =
    # Use the requirements file in the docs repo:
    -r{toxinidir}/autokey.github.io/requirements.txt
    dbus-python
    sphinx-toolbox
    -e ./autokey
commands =
    sphinx-build -b html autokey.github.io autokey.github.io/_build/html
