name: Build Autokey pages
on: 
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: install git
        run: |
          sudo apt-get install git -y

      - name: clone and install autokey
        run: |
          git clone https://github.com/autokey/autokey
          cd autokey
          pip install .
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
      - name: install sphinx and dependencies
        run: pip install -r requirements.txt
      - name: build sphinx site
        run: |
          mkdir docs
          sphinx-build -a -E -b html ./ docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs
      
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: sphinx-build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
